#!/usr/bin/env bash

# VARIABLES ###
SW_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"
SW_NAME=`basename ${0:-emulator}`
JAVA_EXEC=`which java`
JAVA_VERSION=`${JAVA_EXEC} -version 2>&1 | head -n 1 | awk '{ print $3 }'`
NOHUP_EXEC=`which nohup`
PID_DIR=${SW_HOME}/tmp
PID_FILE=${PID_DIR}/${SW_NAME}.pid
DEBUG_PORT=9999

# FUNCTIONS ###
function print_help {
cat<<EOF
Usage: ${GRE}${SW_NAME}${NOR} COMMAND
emulator deployer  (src, bin).
COMMAND
    src         deploy the emulator for development environment
    bin         deploy the emulator for execution environment
EOF
}

function enable_colors_if_supported {

if test -t 1; then
    # see if it supports colors...
    NCOLOR=$(tput colors)

    if test -n "$NCOLOR" && test $NCOLOR -ge 8; then
        NOR="$(tput sgr0)"
        RED="$(tput setaf 196)"
        GRE="$(tput setaf 40)"
    fi
fi

OK="[${GRE}ok${NOR}]"
KO="[${RED}ko${NOR}]"

}


function log_start_msg {

echo "${GRE}CISE emulator deployer${NOR}"
echo "Java path:    ${JAVA_EXEC}"
echo "Java version: ${JAVA_VERSION}"

}



function src {
echo execute copy from the cise-mvn-repo.tar.gz to main project and all sub module project that require it
}

function bin {
echo validate the prerequisite and if compliant define setup.sh to inicialise execution context
}


# MAIN ###
enable_colors_if_supported

cd ${SW_HOME}

case $1 in
    src)
        tar -xzvf cise-emulator-src.tar.gz
        echo "should copy the cise-mvn-repo in main project as well as sub module"
        src
        exit 0
        ;;
    bin)
        tar -xzvf cise-emulator-bin.tar.gz
        bin
        exit 0
        ;;
    *)
        print_help
        exit 0
        ;;
esac

exit 0