= CISE Emulator

Jason Gonin <jason.gonin@ext.ec.europa.eu> v1.1, 2019-08-19 :page-layout: docs :imagesdir: assets/images :homepage: https://webgate.ec.europa.eu/CITnet/stash/projects/MAREX/repos/cise-emu/browse :numbered:
:source-highlighter:
Coderay coderay
ifndef::env-site[]
:toc: right
:idprefix:
:idseparator: -
//:icons: font
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:source-language: bash

== Overview

The CISE Emulator is an application to receive and send tracks messages, conform to the Cise Protocole.

== Requirements

The application should preferably installed on a linux machine.
Theoretically should work also in any Operative System supporting Java and having a bash shell support but it has only been tested in a GNU/Linux server.

The server should be installed with:

- Java 1.8
- Maven 3.5+

== Compilation

Clone the git repository:

[source,bash]
----
...$ git clone https://webgate.ec.europa.eu/CITnet/stash/projects/MAREX/repos/cise-emu/browse
----

After cloning the git repository is possible to compile the project using maven.

WARNING: To compile the software it's mandatory to send an email to the JRC CISE Team <JRC-CISE@ec.europa.eu> requesting the content of the cise-mvn-repo directory.
Once received, *please copy the file ais-mvn-repo.tgz in the project directory* and proceed with the following steps.

[source,bash]
----
...$ cd cise-emulator
...$ tar xvfz cise-mvn-repo.tgz
...$ mvn clean install
----

== Preparing the software

When the compilation will be finished (with a BUILD SUCCESSFUL in the standard output) it will be created a distribution package that can be used to run the software.

[source,bash]
----
...$ cd target
...$ mv cise-emulator-bin.tar.gz /my/installation/path
...$ cd /my/installation/path
...$ tar xvfz cise-emulator.tar.gz
...$ cd cise-emulator-bin
----

== Running the AIS Adaptor

The ais-adaptor application can be started by using a script `emulator` in the distribution root path.
Using the command:

The command:

[source,bash]
----
...$ ./emulator run
----

it will be possible to start emulator in foreground.
While to run it in background is possible to launch it with:

[source,bash]
----
...$ ./emulator start
----

.Next steps
NOTE: Please refer to the link:ais-docs/src/main/asciidoc/configuration.adoc[configuration chapter] to configure the adaptor with the parameters specific to the public administration where the ais-adaptor will be installed.

