
export default  class MessageType {
    static TEXT_MESSAGE = 'TEXT_MESSAGE';
    static USER_JOINED = 'USER_JOINED';
    static USER_LEFT = 'USER_LEFT';
    static USER_JOINED_ACK = 'USER_JOINED_ACK';

    static UTIL_QUERY_TEMPLATE = 'UPDATE_QUERY_TEMPLATE';
    static UTIL_RESPONSE_TEMPLATE = 'UPDATE_RESPONSE_TEMPLATE';
    static UTIL_QUERY_PAYLOAD = 'UPDATE_QUERY_TEMPLATE';
    static UTIL_RESPONSE_PAYLOAD = 'UPDATE_RESPONSE_TEMPLATE';

    static MASTER = 'MASTER';
    static MASTER_IN = 'MASTER_INCOMING';
    static MASTER_OUT = 'MASTER_OUTGOING';


    static SECONDARY_OUT_ASYNC = 'SECONDARY_OUTGOING_ACKNOLEDGE_ASYNC';
    static SECONDARY_IN_SYNC = 'SECONDARY_INCOMING_ACKNOLEDGE_SYNC';

    static SECONDARY_OUT_SYNC = 'SECONDARY_OUTGOING_ACKNOLEDGE_SYNC';
    static SECONDARY_IN_ASYNC = 'SECONDARY_INCOMING_ACKNOLEDGE_ASYNC';
}
