
export default  class MessageType {
    static TEXT_MESSAGE = 'TEXT_MESSAGE';
    static USER_JOINED = 'USER_JOINED';
    static USER_LEFT = 'USER_LEFT';
    static USER_JOINED_ACK = 'USER_JOINED_ACK';

    static UTIL_QUERY_TEMPLATE = 'UPDATE_QUERY_TEMPLATE';
    static UTIL_RESPONSE_TEMPLATE = 'UPDATE_RESPONSE_TEMPLATE';
    static UTIL_QUERY_PAYLOAD = 'UPDATE_QUERY_TEMPLATE';
    static UTIL_RESPONSE_PAYLOAD = 'UPDATE_RESPONSE_TEMPLATE';

    static MASTER_= 'MASTER';




    static MASTER_IN_PUSH = 'MASTER_INCOMING_PUSH';
    static MASTER_IN_PULLQUERY = 'MASTER_INCOMING_PULLQUERY';
    static MASTER_IN_PULLREQUEST = 'MASTER_INCOMING_PULLREQUEST';
    static MASTER_IN_PUBLISH2SUBSCRIBER = 'MASTER_INCOMING_PUBLISH2SUBSCRIBER';
    static MASTER_IN_SUBSCRIBE2PUBLISHER = 'MASTER_INCOMING_SUBSCRIBE2PUBLISHER';

    static MASTER_OUT_PUSH = 'MASTER_OUT_PUSH';
    static MASTER_OUT_PULLQUERY = 'MASTER_OUT_PULLQUERY';
    static MASTER_OUT_PULLREQUEST = 'MASTER_OUT_PULLREQUEST';
    static MASTER_OUT_PUBLISH2SUBSCRIBER = 'MASTER_OUT_PUBLISH2SUBSCRIBER';
    static MASTER_OUT_SUBSCRIBE2PUBLISHER = 'MASTER_OUT_SUBSCRIBE2PUBLISHER';

    static SECONDARY_OUT_SYNC = 'SECONDARY_OUT_ACKNOLEDGE_SYNC';
    static SECONDARY_OUT_ASYNC = 'SECONDARY__OUT_ACKNOLEDGE_ASYNC';
    static SECONDARY_IN_SYNC = 'SECONDARY_IN_ACKNOLEDGE_SYNC';
    static SECONDARY_IN_ASYNC = 'SECONDARY_IN_ACKNOLEDGE_ASYNC';
