
export default  class MessageType {
    static TEXT_MESSAGE = 'TEXT_MESSAGE';
    static USER_JOINED = 'USER_JOINED';
    static USER_LEFT = 'USER_LEFT';
    static USER_JOINED_ACK = 'USER_JOINED_ACK';

    static UPDATE_QUERY_TEMPLATE = 'UPDATE_QUERY_TEMPLATE';
    static UPDATE_RESPONSE_TEMPLATE = 'UPDATE_RESPONSE_TEMPLATE';
    static UPDATE_QUERY_PAYLOAD = 'UPDATE_QUERY_TEMPLATE';
    static UPDATE_RESPONSE_PAYLOAD = 'UPDATE_RESPONSE_TEMPLATE';

    static MASTER_PUSH = 'MASTER_PUSH';
    static MASTER_PULLQUERY = 'MASTER_PULLQUERY';
    static MASTER_PULLREQUEST = 'MASTER_PULLREQUEST';
    static MASTER_PUBLISH2SUBSCRIBER = 'MASTER_PUBLISH2SUBSCRIBER';
    static MASTER_SUBSCRIBE2PUBLISHER = 'MASTER_SUBSCRIBE2PUBLISHER';



    static MASTER_INCOMING_PUSH = 'MASTER_INCOMING_PUSH';
    static MASTER_INCOMING_PULLQUERY = 'MASTER_INCOMING_PULLQUERY';
    static MASTER_INCOMING_PULLREQUEST = 'MASTER_INCOMING_PULLREQUEST';
    static MASTER_INCOMING_PUBLISH2SUBSCRIBER = 'MASTER_INCOMING_PUBLISH2SUBSCRIBER';
    static MASTER_INCOMING_SUBSCRIBE2PUBLISHER = 'MASTER_INCOMING_SUBSCRIBE2PUBLISHER';

    static MASTER_OUTGOING_PUSH = 'MASTER_OUTGOING_PUSH';
    static MASTER_OUTGOING_PULLQUERY = 'MASTER_OUTGOING_PULLQUERY';
    static MASTER_OUTGOING_PULLREQUEST = 'MASTER_OUTGOING_PULLREQUEST';
    static MASTER_OUTGOING_PUBLISH2SUBSCRIBER = 'MASTER_OUTGOING_PUBLISH2SUBSCRIBER';
    static MASTER_OUTGOING_SUBSCRIBE2PUBLISHER = 'MASTER_OUTGOING_SUBSCRIBE2PUBLISHER';

    static SECONDARY_ACKNOLEDGE_SYNC = 'SECONDARY_ACKNOLEDGE_SYNC';
    static SECONDARY_ACKNOLEDGE_ASYNC = 'SECONDARY_ACKNOLEDGE_SYNC';

    static SECONDARY_INCOMING_ACKNOLEDGE_SYNC = 'SECONDARY_ACKNOLEDGE_SYNC';
    static SECONDARY_INCOMING_ACKNOLEDGE_ASYNC = 'SECONDARY_ACKNOLEDGE_SYNC';

    static SECONDARY_OUTGOING_ACKNOLEDGE_SYNC = 'SECONDARY_ACKNOLEDGE_SYNC';
    static SECONDARY_OUTGOING_ACKNOLEDGE_ASYNC = 'SECONDARY_ACKNOLEDGE_SYNC';
}